site_name: Rooster Wars Whitepaper V1
theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  font:
    text: Poppins
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
  palette: #1
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: orange
    - scheme: slate #2
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: white
      accent: amber
nav:
  - Introduction: README.md
  - Our Philosophy: our-philosophy.md
  - EGG-SALE:
      - egg-sale/index.md
      - Roosters:
          - egg-sale/roosters/index.md
          - Starter Roosters: egg-sale/roosters/free-starter-roosters.md
          - NFT Roosters: egg-sale/roosters/nft-roosters-pure-breed.md
      - GAFFs and Gems: egg-sale/gaffs-and-gems.md
  - Phase 1:
      - Gameplay: phase1/gameplay.md
      - $Gallonium: phase1/$gallonium.md
      - Arena (PvP):
          - phase1/arena/index.md
          - Diminishing Returns: phase1/arena/diminishing-returns.md
      - Adventure Mode (PvE):
          - phase1/adventure-mode/index.md
          - Training: phase1/adventure-mode/training-roosters.md
      - Rooster Battle: phase1/rooster-battle.md
  - Phase 2:
      - Breeding: phase2/breeding.md
      - Hens: phase2/hens.md
  - Phase 3:
      - Land and Buildables: phase3/land-and-buildables.md
      - Expedition: phase3/expedition.md
  - Game Rewards:
      - game-rewards/index.md
      - Arena: game-rewards/reward-arena.md
      - Adventure: game-rewards/reward-adventure.md
      - Season: game-rewards/reward-season.md
      - FAQ: game-rewards/reward-faqs.md
  - $GWIT Tokenomics:
      - Utility: tokenomics/utility.md
      - Allocation: tokenomics/allocation.md
      - Sale rounds: tokenomics/token-sale-rounds.md
      - Vesting Schedules: tokenomics/vesting-schedule.md
  - DeFI Ecosystem:
      - defi/index.md
      - Farming: defi/farming.md
      - Swap: defi/swap.md
  - Technology: technology.md
  - Roadmap: roadmap.md
  - Team & Partners: team-and-partners.md
  #- Contracts: smart-contracts.md

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Use extra CSS to customize styles, based on theme
extra_css:
  - css/images.css
