site_name: Rooster Wars (v1)
site_url: https://whitepaper.roosterwars.io
extra:
  homepage: https://www.roosterwars.io
theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  font:
    text: Poppins
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
  palette: #1
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: orange
    - scheme: slate #2
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: white
      accent: amber
nav:
  - Introduction: README.md
  - Our Philosophy: our-philosophy.md
  - The Three Economies: three-economies.md
  #- FAQ: faq.md
  - Value Accrual:
      - Professional Roosters: value/professional.md
      - Backyard Roosters: value/backyard.md
  - Tokenomics:
      - Tokenomics: tokenomics/index.md
  - DeFi Ecosystem:
      - DeFi Ecosystem: defi/index.md
  #- Technology: technology.md
  - Roadmap: roadmap.md
  - Team & Partners: team-and-partners.md
  #- Contracts: smart-contracts.md

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Use extra CSS to customize styles, based on theme
extra_css:
  - css/images.css
