site_name: Rooster Wars (V1)
site_url: https://whitepaper.roosterwars.io
extra:
  homepage: https://www.roosterwars.io
theme:
  name: material
  favicon: images/logo.png
  logo: images/logo.png
  font:
    text: Poppins
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
  palette: #1
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: orange
    - scheme: slate #2
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: white
      accent: amber
nav:
  - Introduction: README.md
  - Our Philosophy: our-philosophy.md
  - EGG-SALE:
      - EGG-Sale: egg-sale/index.md
  - FAQ:
      - Phase 1: faq/p1.md
      - Phase 2: faq/p2.md
      #- Phase 3: faq/p3.md
  - Gameplay:
      - Roosters:
          - Roosters: gameplay/roosters/index.md
          - Starter Roosters: gameplay/roosters/free-starter-roosters.md
          - NFT Roosters: gameplay/roosters/nft-roosters-pure-breed.md
      - GAFFs and Gems: gameplay/gaffs-and-gems.md
      - Phase 1:
          - Gameplay: gameplay/phase1/gameplay.md
          - $Gallonium: gameplay/phase1/$gallonium.md
          - Arena (PvP):
              - Arena Mode: gameplay/phase1/arena/index.md
          - Adventure Mode (PvE):
              - Adventure Mode: gameplay/phase1/adventure-mode/index.md
              - Training: gameplay/phase1/adventure-mode/training-roosters.md
          - Rooster Battle: gameplay/phase1/rooster-battle.md
      - Phase 2:
          - Breeding: gameplay/phase2/breeding.md
          - Hens: gameplay/phase2/hens.md
      - Phase 3:
          - Land and Buildables: gameplay/phase3/land-and-buildables.md
          - Expedition: gameplay/phase3/expedition.md
      - Game Mode Rewards:
          - Game Mode Rewards: gameplay/game-rewards/index.md
          - Arena: gameplay/game-rewards/reward-arena.md
          - Adventure: gameplay/game-rewards/reward-adventure.md
          - Season: gameplay/game-rewards/reward-season.md
          - Rooster Battle: gameplay/game-rewards/reward-battle.md
  - $GWIT Tokenomics:
      - Utility: tokenomics/utility.md
      - Allocation: tokenomics/allocation.md
      - Sale rounds: tokenomics/token-sale-rounds.md
      - Vesting Schedules: tokenomics/vesting-schedule.md
  - DeFI Ecosystem:
      - DeFI Ecosystem: defi/index.md
      - Farming: defi/farming.md
      - Swap: defi/swap.md
  - Technology: technology.md
  - Roadmap: roadmap.md
  - Team & Partners: team-and-partners.md
  #- Contracts: smart-contracts.md

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Use extra CSS to customize styles, based on theme
extra_css:
  - css/images.css
