site_name: Rooster Wars Whitepaper
theme:
  name: material
  favicon: images/rooster-coin.png
  font:
    text: Poppins
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
  palette: #1
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: orange
    - scheme: slate #2
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: amber
      accent: amber
nav:
  - "README.md"
  - "our-philosophy.md"
  - EGG-SALE:
      - egg-sale.md
      - Roosters:
          - roosters.md
          - free-starter-roosters.md
          - nft-roosters-pure-breed.md
      - "gaffs-and-gems.md"
  - Phase 1:
      - "gameplay.md"
      - "$energy.md"
      - Arena (PvP):
          - "arena-pvp.md"
          - "diminishing-returns.md"
      - Adventure Mode (PvE):
          - "adventure-mode.md"
          - "training-roosters.md"
      - "rooster-battle.md"
  - Phase 2:
      - "breeding.md"
      - "hens.md"
  - Phase 3:
      - "land-and-buildables.md"
      - "expedition.md"
  - Game Rewards:
      - "reward-system.md"
      - "reward-arena.md"
      - "reward-adventure.md"
      - "reward-season.md"
      - "reward-faqs.md"
  - $Rooster Tokenomics:
      - "utility.md"
      - "allocation.md"
      - "token-sale-rounds.md"
      - "vesting-schedule.md"
  - DeFI Ecosystem:
      - "defi-ecosystem.md"
      - "farming-$rooster.md"
      - "swap.md"
  - "technology.md"
  - "roadmap.md"
  - "team-and-partners.md"
  - "smart-contracts.md"

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Use extra CSS to customize styles, based on theme
extra_css:
  - "css/images.css"
